version: '3'
services:
  database:
    image: postgres:11
    ports:
      - "5444:5432"
    volumes:
      - ./storage/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=localpassword
      - POSTGRES_DB=vfstracker

  selenium:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"

  vfsbot:
    image: maksimhawkins/vfs-tracker-bot:latest
    depends_on: [database, selenium]
    environment:
      - DATABASE_HOST=database
      - DATABASE_PORT=5432
      - BOT_TOKEN=5113677358:AAFnOTFN2a0lJBYS6QVQ6Msv5L0xP5IL930
      - SELENIUM_HOST=selenium