version: '3'
services:
  database:
    image: postgres:11
    ports:
      - "5432:5432"
    volumes:
      - ./storage/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=localpassword
      - POSTGRES_DB=vfstracker